### ISSUE TITLE
Error message for date and time format

### ISSUE THREAD

**Issue by Marcell-Juhasz** [Marcell-Juhasz/secret-diary#22]
I can remove the following check, so if the number of lines are matching, but there is some other problem, the user will see the expected value.
// Should be removed ?
`val messageWrongDate1 =
    "Make sure your date/time has the following format with the correct values: \"yyyy-MM-dd HH:mm:ss\""`
`assertTrue(messageWrongDate1, userOutput1.contains(dateText1))`

**Comment by RedJocker** [comment]
Showing the expected value is not a problem. But they should not be able to pass easily  just by hardcoding values that are expected. 
If it is possible for users to pass with hardcoded values you can have more test cases with different expected values to make it unlikely that they can have one hardcoded value. 
Another option is to include some randomness on the time expected, but be really careful with randomness, you also don't want to have tests that are inconsistent, that is passing when it should fail or failing when it should pass.

**Comment by Marcell-Juhasz** [comment]
I don't exactly know why the test was not working for the second reviewer, but I've just committed some changes. Removed the lines mentioned above and made it work with random seconds: shadowLooper.idleFor(Duration.ofSeconds(randSec))

**Comment by RedJocker** [comment]
I think I answered this on the report. They were having problems because test is using Locale and they were doing timestamp more manually using toString, but that approach was not taking locale into account so it was off.

I'm on mobile right now, but later I can put a sample of the code used by user.

If I'm not mistaken I have added locale as a requirement on description already

**Comment by RedJocker** [comment]
this is the code from the tester [282739162](https://hyperskill.org/profile/282739162)

the part that matters:

```

val newTextCustom = "${
                    Clock.System.now().toString().replace("T", " ").substringBefore(".")
                }\n${editText.text}\n\n${textView.text}"
                
```

and the whole activity

```
package org.hyperskill.secretdiary

import android.os.Bundle
import android.util.Log
import android.widget.Button
import android.widget.EditText
import android.widget.TextView
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import kotlinx.datetime.Clock
import java.text.SimpleDateFormat
import java.util.*



class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val btn = findViewById<Button>(R.id.btnSave)
        val editText = findViewById<EditText>(R.id.etNewWriting)
        val textView = findViewById<TextView>(R.id.tvDiary)
        btn.setOnClickListener {
            if (editText.text.isNotBlank()) {
                val simpleDateFormat = SimpleDateFormat(
                    "yyyy-MM-dd HH:mm:ss",
                    Locale.getDefault()
                ).format(Clock.System.now().toEpochMilliseconds())

                val newTextCustom = "${
                    Clock.System.now().toString().replace("T", " ").substringBefore(".")
                }\n${editText.text}\n\n${textView.text}"
                val newTextImported =
                    "${simpleDateFormat}\n${editText.text}${if (textView.text.isNotBlank()) "\n\n${textView.text}" else ""}"
                Log.i("TimeRaw", Clock.System.now().toString())
                Log.i("TimeCustom", Clock.System.now().toString().replace("T", " ").substringBefore("."))
                Log.i("TimeDateFormat", SimpleDateFormat(
                    "yyyy-MM-dd HH:mm:ss",
                    Locale.getDefault()
                ).format(Clock.System.now().toEpochMilliseconds()))
                textView.text = newTextCustom
                editText.text.clear()
            } else {
                Toast.makeText(
                    applicationContext,
                    "Empty or blank input cannot be saved",
                    Toast.LENGTH_SHORT
                ).show()
            }
        }
    }

}
```

**Comment by RedJocker** [comment]
So a user that is on timezone UTC won't have problems with that code, but any other timezone the test code will take the timezone into consideration and user code won't.

**Comment by RedJocker** [comment]
> but I've just committed some changes

don't forget to push the commited changes so I can see it, also don't forget to reference the issue number on the commit message so that I can see the commit related to this issue here in the issue page

**Comment by Marcell-Juhasz** [comment]
I forgot the reference, but you can see it on the "stepik" branch

**Comment by RedJocker** [comment]
commit a2fbc7f4aa9e43cc3ecc75ea6e981f97545c8613

**Comment by RedJocker** [comment]
I think you can leave just the assertEquals assertions on Stage2UnitTest.testShouldCheckSaving()

Now I don't know about remaining stages, maybe same refactoring logic applies to next stages as well.

**Comment by Marcell-Juhasz** [comment]
This is good news that there is a topic about Locale. I guess we should mention in the stage description that the time should be UTC time.

**Comment by RedJocker** [comment]
> I guess we should mention in the stage description that the time should be UTC time.

I have already added this on the description

*To produce the timestamp use SimpleDateFormat with Locale.getDefault() so that the timestamp produced is aware of user's timezone while being produced*

The idea was to require the use of Locale on the code. 

You can change this if you want to require UTC instead, but you will have to change tests also


-----

> This is good news that there is a topic about Locale. 

Hmmm... I had not seen that yet, I did see there is already a Kotlinx datetime topic and added that, I will add the Locale topic as well. I think both topics are relatively new, so I was not really aware of them. I'm more aware of new topics on android track, because they talk about that on meetings, but those are kotlin track topics.

**Comment by RedJocker** [comment]
by the way if you think a certain topic should be included just tell me which topic in which stage and I can include it. If there is some subject on the project not covered by topic you can request that topic, it will take a while for someone to write it, but eventually it will be created. 
It is also possible to try writing a topic yourself too, it will go though all the production process with the topic content team and probably many revisions of the text until the final text, but you can do it.

**Comment by Marcell-Juhasz** [comment]
I've committed the date and time changes for all the stages (2, 3, 4).

-I've modified the error message mentioned the UTC time zone: "Make sure you are using UTC time zone and the date/time has the following format with the correct values: \"yyyy-MM-dd HH:mm:ss\""

-I appended the description to let the user know that the date and time values should be in UTC time zone.


commit: 7a8e709a03af98588fba6f8975f1e852df9cd2f3

**Comment by Marcell-Juhasz** [comment]
I've committed the changes on the solution branch, since as you mentioned on stepik there is no solution for testing

**Comment by RedJocker** [comment]
> I appended the description to let the user know that the date and time values should be in UTC time zone.

I don't see any changes in expected values by tests in this commit you tagged, and tests were taking locale into account. I believe that if users uses UTC as locale they won't pass tests. 

look this for example https://github.com/Marcell-Juhasz/secret-diary/blob/2dfbb258ce6918916659fed336d87aa4c4a9ebd6/secret-diary/stage2/src/test/java/org/hyperskill/secretdiary/Stage2UnitTest.kt#L88


also if you are changing your requirements you should change your solution to attend the new requirements.

Personally I would prefer keeping Locale.getDefault, so that raw approach using toString would be wrong on purpose, but it is your call. Just remember that changing requirements means changing reference solution and changing test expected values to match requirements

**Comment by Marcell-Juhasz** [comment]
You say that "I believe that if users uses UTC as locale they won't pass tests."
But also "Personally I would prefer keeping Locale.getDefault"
If we keep the getDefault, then we should let the users know that they should use the default time zone (UTC).
Otherwise, they run into similar problems one of the reviewers did.

So, what is your suggestion to avoid time zone conflicts?

**Comment by RedJocker** [comment]
Oh, you have wrong understanding on Locale.getDefault() it is not related to UTC, it is based on the enviroment in which is running

**Comment by RedJocker** [comment]
try running the user code on a debugger to better understand what is the issue he was having

**Comment by Marcell-Juhasz** [comment]
(Sorry, accidentally I edited your comment instead of quoting it)
> Oh, you have a wrong understanding of Locale.getDefault() it is not related to UTC, it is based on the environment in which is running

Okay, I think I know what's the problem.
I had the correct understanding at the beginning, that the Locale.getDefault() gives back the correct time (the time on the user's computer).
But, I just realized that the Clock.System.now() DON'T!
(It was straightforward to me, that "System" refers to the system on which the program is running, but it seems this is not the case.)

Anyway, the first version of the test is how I want the user to write their solution: using the time in their own time zone. Of course, if I write a timestamp in my diary, I use my own clock.
So, If you agree, I'm gonna add 2 Asserts to check the solution:
1. Check if the time format is good (maybe with regex)
2. Check if the HOUR is matching. If not, remind them to use their local time zone

**Comment by RedJocker** [comment]
ok, just don't forget to make clear on error messages about expected X actual so that users understand what they did wrong and what they should do to fix it

**Comment by Marcell-Juhasz** [comment]
I have implemented a more detailed check, so the user will get more accurate feedback about what they did wrong: e51750ee5ee7b27a84b6f3f1fa4f339500495cb2

**Comment by RedJocker** [comment]
ok this looks better, I tested a little bit and it seems to be working. 

I am just a little concerned with the code duplication, I think there could be a function that is reused to do these common assertions instead duplicating the code. That function could be written on the bottom of the AbstractUnitTest class

But we can leave as it is for now. We still don't have a third tester for the project and I would like to update it before a third tester starts testing it.

I think this can be closed for now unless you still want to do something about this issue
